
export const ADD_PLACE    = 'ADD_PLACE';
export const SET_PLACES   = 'SET_PLACES';
export const GET_PLACES   = 'GET_PLACES';

export const SET_COMPONENT_ID = 'SET_COMPONENT_ID';
export const INCREASE_BADGE_NUMBER = 'INCREASE_BADGE_NUMBER';
export const DECREASE_BADGE_NUMBER = 'DECREASE_BADGE_NUMBER';

export const TRY_AUTH = 'TRY_AUTH';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
